### ISSUE TITLE
Dudas Domain Model & UML

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP9Entrega#1]
# ATENCIÓN: En estos momentos este documento incluye qué falta por hacer del Domain Model y UML, no sólo las dudas.

Level C:
- Repasar

Level B:
- Repasar

Level A:
- Repasar

En general:
- Modificar commentedEntity ya que ahora concierne a un trainer y éste no posee un título ni una descripción. También hay que poner la relación entre ambas entidades (aggregation).
- Modificar socialIdentity ya que ahora no cuelga de Customer sino de Actor (HECHO).

**Comment by ManuelLR** [comment]
Ya se han resuelto todos estos problemas y de manera distinta a la comentada anteriormente
