### ISSUE TITLE
[Corregir] Se puede crear un SpamTerm con el term Vacío/Blank e incluso null

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#100]

**Comment by ManuelLR** [comment]
@CeuxDruman Niño, actualiza de Develop antes de seguir haciendo test que ya estaba cambiado al poner el campo como id xD

**Comment by ManuelLR** [comment]
@CeuxDruman Confirma cuando tires de Develop si continua

**Comment by CeuxDruman** [comment]
@ManuelLR actualicé de Develop justo antes de hacer el test. Probaré luego de nuevo.

**Comment by CeuxDruman** [comment]
@ManuelLR No se a que te refieres con que has puesto "el campo como id", si te refieres a que lo has indexado para alguna query tampoco veo que tenga relación con la resolución de este Issue, pero he vuelto a ejecutar los test tras traerme todo Develop ahora mismo y no se soluciona. Si gue dejándome crear SpamTerms vacíos y nulos.

**Comment by CeuxDruman** [comment]
@ManuelLR PD: No ha habido ningún cambio nuevo en cuanto a SpamTerms desde que hice los test y publiqué el Issue.

**Comment by ManuelLR** [comment]
Visto, añadir @NotBlank y @NotNull en el domain y debería solucionar todo
