### ISSUE TITLE
[Corregir] Como cualquier user e incluso deslogueado puedo crear una carpeta para cualquier otro user

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#101]

**Comment by ManuelLR** [comment]
@CeuxDruman Repetido, usar el #102

**Comment by CeuxDruman** [comment]
@ManuelLR No es lo mismo, el #102 se refiere que ningún usuario debería poder crear carpetas del sistema. El #101 a que ningún usuario debería poder crear carpetas para otros usuarios.

**Comment by ManuelLR** [comment]
La restricción viene a ser la misma, que la carpeta no es del usuario actual

**Comment by CeuxDruman** [comment]
@ManuelLR Sigues sin entenderlo. El #102 es que cualquier usuario (PARA SÍ MISMO) no debería poder crear carpetas del sistema (isSystem = true) y sin embargo la aplicación te deja hacerlo.
