### ISSUE TITLE
[Corregir] Como cualquier user e incluso deslogueado puedo crear una carpeta del sistema

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#102]

**Comment by ManuelLR** [comment]
Ya debe estar solventado.
**NO LO HE PROBADO**
Comprueba con los test o la vista que está todo OK.

**Comment by CeuxDruman** [comment]
@ManuelLR A mi me sigue dejando crear carpetas para otros usuarios y carpetas del sistema.

**Comment by ManuelLR** [comment]
@CeuxDruman Si que te deja hacerlas pero es mentira (el #102) porque no compruebas a quien se la ha creado, cuando lo veas verás que se la ha creado al customer 2 ya que lo que hago es asignarse lo al que está logueado

**Comment by ManuelLR** [comment]
@ManuelLR Mira el código en el que se cambio, lo soluciono sustituyendo

**Comment by ManuelLR** [comment]
@ManuelLR Ahhhh coño, ahora lo entiendo, pues ni idea la verdad luego lo miro. No se si lo comprueba o no la verdad pero puede que igualmente te deje crearla pero le desactive el isSystem antes de guardar. Repito _No se si se controla_

**Comment by CeuxDruman** [comment]
Corregido y probado.
