### ISSUE TITLE
Print a invoice no va bien

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP9Entrega#116]
Pagas el gimnasio de Cádiz con el Customer1.
Te vas a Invoice
Crear invoice
Eliges que te saque el de Cádiz (tiene un cost de 20).
Te imprime tanto el de Cádiz como el de Sevilla (con un cost de 50).

**Comment by migrodcab** [comment]
Listo @c25909813b67d7762c0369f60d3b9bcee1aba47e
