### ISSUE TITLE
Duda sobe atributos Date y StartingMoment

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP9Entrega#12]
Ambos se implementan con un tipo Date, pero en la base de dato guardan la misma información. ¿Se podría poner como un solo atributo y después mostrarse en dos columnas distintas con el format?

**Comment by ManuelLR** [comment]
Si, es como se debe hacer

Se refiere a Activity !

**Comment by CeuxDruman** [comment]
Resuelto.
