### ISSUE TITLE
[Corregir] Se puede registrar un Trainer con username null

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#127]
**CUIDADO**: Seguramente también sea aplicable a registrar un Customer.

**Comment by ManuelLR** [comment]
@CeuxDruman Ignora el error ya que eso casi lo daban hecho y en la aplicación es imposible. Aprovechó y te digo que cualquier tipo de actor se crea desde actorFormService así que puede que si lo haces directamente no se compruebe todo

**Comment by CeuxDruman** [comment]
Lo he corregido en el servicio, al registrar un Customer y Trainer.
