### ISSUE TITLE
CAMBIOS MODELOS UML

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#17]
**En Invoice:**
-Cambiado createdMoment por creationMoment
-Quitadas TODAS las restricciones de VAT y puesto sólo: NotBlank (En Java debe ir NotNull también)
**En Activity:**
-Quitadas las 2 fechas (date y startingTime) y puesto sólo 1 fecha llamada startingMoment

**Comment by ManuelLR** [comment]
Listo
