### ISSUE TITLE
[Models] Añadir atributo a actorForm

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP9Entrega#23]
Añadir atributo picture que es una url que puede estar vacía

**Comment by ManuelLR** [comment]
Solo faltaría añadirlo en los modelos

**Comment by guillermo-ag-95** [comment]
Listo https://github.com/DPIRPSG/DP9Entrega/commit/29c9e367f88f9655ebda68351e38543ce590cbb5
