### ISSUE TITLE
[Models] Trainer has Service????

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP9Entrega#33]
No sería Trainer specialise in a Service?????

**Comment by CeuxDruman** [comment]
Estoy de acuerdo en cambiar "has" por "specialized in".

**Comment by guillermo-ag-95** [comment]
Listo https://github.com/DPIRPSG/DP9Entrega/commit/26dea0bb32f16aa2421772120c3c65b17954ac16
