### ISSUE TITLE
[Urgente! ]  Añadir nombre de usuario en Telegram

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP9Entrega#39]

**Comment by ManuelLR** [comment]
Urgente!

**Comment by migrodcab** [comment]
@ManuelLR A ver si se lo pone ya!

**Comment by ManuelLR** [comment]
@migrodcab Moriremos todos y @guillermo-ag-95 seguirá sin alias de telegram

**Comment by ManuelLR** [comment]
@guillermo-ag-95 VENGAAAAAAAA

**Comment by ManuelLR** [comment]
@ManuelLR Te esperamos 💋💋

**Comment by ManuelLR** [comment]
@ManuelLR Ya te elegí nombre y todo @Guillermeishious

**Comment by migrodcab** [comment]
@ManuelLR GuillermoElSinAlias mejor

**Comment by ManuelLR** [comment]
@migrodcab Me parece mejor la verdad xD

**Comment by ManuelLR** [comment]
@ManuelLR @guillermo_ag y @guillermo_ag_95 están libres!
