### ISSUE TITLE
Buscar Trainer por keyword

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP9Entrega#40]
al buscar solo mira que el keyword sea exactamente igual a un string de la lista de Skills, likes o dislikes.
No se puede hacer de otra forma con queries. Una solución sería hacerlo en los servicios, pero habria que traerse toda la base de datos lo cual es ineficiente.
Preguntar en revisión

**Comment by guillermo-ag-95** [comment]
Corregido. El cambio se subió a Develop en su día.
