### ISSUE TITLE
¿¿ @ElementCollection en pictures de Room ??

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#50]
En la Collection<picture> de la entidad Room se le ha puesto el parámetro @ElementCollection, que según dice la teoría (o al menos eso he podido leer y entender), se pone cuando tienes una colección que forma parte de una relación con otra clase y que además esa clase de DataType.

En este caso pictures no es una relación con otra clase (pictures es un atributo de la clase, no otra entidad relacionada con Room) y tampoco es un DataType. Por lo que no le veo sentido alguno a ese parámetro en este sitio.

NOTA: Podéis echarle un ojo a la diapositiva 32 del Tema 3, donde se explica para qué sirve este parámetro.

**Comment by migrodcab** [comment]
@CeuxDruman Ups, hay que revisar el domain muy bien

**Comment by CeuxDruman** [comment]
**CUIDADO**: Está puesto en todos los Collections del domain....
