### ISSUE TITLE
¿ ${id} en el tag selectMult ?

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#51]
En el tag selectMult se hace uso de un parámetro "id" que no se pide ni se pasa de ninguna manera y en ningún caso, por lo que creo que sobra por completo:

<%-- Attributes --%> 

<%@ attribute name="path" required="true" %>
<%@ attribute name="code" required="true" %>
<%@ attribute name="items" required="true" type="java.util.Collection" %>
<%@ attribute name="itemLabel" required="true" %>

<%-- Definition --%>

```
<div>
    <form:label path="${path}">
        <spring:message code="${code}" />
    </form:label>   
    <form:select id="${id}" path="${path}" items="${items}" itemLabel="${itemLabel}" itemValue="id" multiple="multiple">
    </form:select>
    <form:errors path="${path}" cssClass="error" />
</div>
```

**Comment by migrodcab** [comment]
@CeuxDruman 1.- infórmate de para que sirve

**Comment by migrodcab** [comment]
@CeuxDruman 2.- Venía hecho por los profesores

**Comment by CeuxDruman** [comment]
@migrodcab No venía hecho por lo profesores. El que venía hecho es el "select" asecas, en el que sí se hace un uso correcto del parámetro "id" ya que se le pide en los <%-- Attributes --%>  y se le pasa en las vistas.

**Comment by ManuelLR** [comment]
mira donde se usa y comprueba para que se usa

**Comment by ManuelLR** [comment]
Al final lo quitaste tu, no?

Si es así cierra el issue

**Comment by CeuxDruman** [comment]
No lo quité a la espera de que me confirmarais que no sirve/se usa para nada. ¿Lo quito?

**Comment by ManuelLR** [comment]
@CeuxDruman Te refieres a quitar el parámetro

**Comment by migrodcab** [comment]
LIsto, pendiente de Ok para cerrar
@07b2649bb89f000c70d71b58d01e40c61a2fc0db

**Comment by ManuelLR** [comment]
OK
