### ISSUE TITLE
Comentar a Inma idea Hackaton!!!!

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP9Entrega#72]

**Comment by ManuelLR** [comment]
pero... cual es? xD

**Comment by CeuxDruman** [comment]
+1 a @ManuelLR

**Comment by ManuelLR** [comment]
@CeuxDruman Recordáis lo que propuse?

**Comment by CeuxDruman** [comment]
A mi nadie me ha contado ninguna idea para el Hackaton, así que si pretendéis que os de la aprobación mañana Inma, al menos comentadla antes con el resto del grupo xD @ManuelLR @migrodcab 

@ManuelLR creo recordar que dijo algo por encima hace tiempo pero no lo recuerdo. Pero @migrodcab ni se ha pronunciado sobre la suya.

**Comment by ManuelLR** [comment]
@CeuxDruman La única que se propuso fue la mía que fue el sistema de inscripciones y resultados de una prueba deportiva
