### ISSUE TITLE
checkCurriculum no deberia ser private?

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP9Entrega#77]

**Comment by migrodcab** [comment]
Solo se usa en el service

**Comment by CeuxDruman** [comment]
Correcto, lo cambias tú o yo cuando me ponga?

**Comment by migrodcab** [comment]
@CeuxDruman Lo hago yo

**Comment by CeuxDruman** [comment]
@migrodcab cuando lo hagas cierra Issue. Ejem.

**Comment by ManuelLR** [comment]
@CeuxDruman Si lo va a hacer él... Porque no se lo asignas a @migrodcab en lugar de quedartelo asignado tú?? XD
