### ISSUE TITLE
Cambiar "Your spam terms" por "System spam terms"

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#80]
Según tengo entendido un spam term va asociado a todo el sistema, no pertenece al admin que lo crea ni tiene ninguna relación con este. Por lo que veo incorrecto el título de "Your spam terms" en el listado de Spam Terms, creo que debería ser "System spam terms", "List of spam terms", o algo por el estilo.

**Comment by ManuelLR** [comment]
@CeuxDruman Lo veo bien. 
Cambialo si quieres

**Comment by CeuxDruman** [comment]
Cambiado.
