### ISSUE TITLE
¿Nombre de los Test de Gym y Activity mal?

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#81]
Según la teoría el nombre de los test debe tener el siguiente formato "EntityServiceTest", además de ir en el paquete "services". Sin embargo los tests de Gym y Activity han sido nombrados por su creador como "GymTest" y "ActivityTest", lo cuál veo mal. 

Además, en el caso de que realmente se estuviera testeando sólo la clase Domain, se debería crear un paquete "domains", incluir ahí estos tests y renombrarlos a "GymDomainTest" y "ActivityDomainTest" respectivamente.

Todo esto lo indico tal y como viene explicado y detallado en teoría (L9: Diap. 56):

> The JUnit classes are not intended to be used in the pre- or the production configurations, but in the development one. Therefore, it should not be placed in “src/main/java”, but in “src/test/java”. Note that we recommend that you should create a package per component kind, e.g., “services”, then a test class per component, e.g., “AnnouncementServiceTest”, and, finally, a “utilities” package in which you must place class “AbstractTest” class that we provide.

**Comment by guillermo-ag-95** [comment]
Listo
