### ISSUE TITLE
Los Actors no deberían poder listar Trainers

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#82]
> 7- A user who is **not authenticated** must be able to:
>      7.2- Navigate through the trainers.

Este es el requisito funcional que habla de poder listar/navegar por los entrenadores del sistema. Imagino que el que lo hizo leyó mal el **not authenticated** y pensó que ponía authenticated. Pero deberíamos corregirlo porque tal y como está ahora mismo la aplicación todos pueden hacerlo. (Autenticados y no autenticados)

**Comment by ManuelLR** [comment]
@CeuxDruman Todos deben poder listsrlos ya que, un requisito el acme 1 era que todo actor podría hacer lo mismo que un no autenticado

**Comment by CeuxDruman** [comment]
Mmm, cierto, no sabía que se aplicaba también a futuros Statements. Si es así estoy de acuerdo.

**Comment by ManuelLR** [comment]
@CeuxDruman Como saber saber no estoy seguro pero creo que si el cliente nos habla de una ampliación del trabajo incluye también que se siga cumpliendo lo anterior
