### ISSUE TITLE
Un Trainer deberia poder hacer todo lo que hace un usuario no autenticado??

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP9Entrega#88]

**Comment by migrodcab** [comment]
Ademas de un Trainer, lo podrían hacer los customers y admins?

**Comment by ManuelLR** [comment]
Confirmado en clase que si

**Comment by migrodcab** [comment]
@ManuelLR Lo se, pero dejalo abierto que hay que hacerlo

**Comment by ManuelLR** [comment]
@migrodcab si, pero estaba asignado, solo cambie asignacion y etiquetas como estoy haciendo con todos

**Comment by migrodcab** [comment]
Listo @1e1afdd2530acffe66a2efc31f76133cf973fd00
