### ISSUE TITLE
No se controla que no se pueda crear/editar (save) un SpamTerm con un "term" (nombre) ya existente

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP9Entrega#91]
@ManuelLR Avísame cuando lo corrijas para hacer los cambios oportunos en el test.

**Comment by ManuelLR** [comment]
@CeuxDruman tu haz el test que falle y así se sabe que debe cambiarse pero no hay ningún sitioque diga eso ya que si no el campo deberiía haberse puesto como unique

**Comment by CeuxDruman** [comment]
@ManuelLR El test no falla precisamente si no se controla.

Yo sólo lo digo porque en clase me dijisteis que era "algo lógico" que no se pudieran repetir y que tú ya lo tenías controlado al menos en la edición según recordabas (no lo veo ni en la creación ni en la edición). Si ves que al final no lo vamos a controlar avísame y quito el test.

**Comment by ManuelLR** [comment]
@CeuxDruman yo dije precisamente que no estaba controlado 😆
Creo que lo mejor sería con controlarlo porque es un caso extraño y no pasa nada por tener dos (quizas por eficiencia) pero que no es como dos personas y un dni.
En caso de cambiarse debería cambiarse en los UMLS y de ahí para arriba

**Comment by ManuelLR** [comment]
falta añadirlo en los modelos uml
