### ISSUE TITLE
Correcciones de la última revisión

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP9Entrega#94]
Sobre la aplicación:
- Controlar el activeMoment al pagar un gym para que si se deja en blanco te diga que está en blanco y que lo rellenes. Ahora mismo sale el "Cannot Commit This Operation".
- Cambiar el nombre de la vista de listar "Activity Plans" por "Activity Plan".
- Modificar la columna "deleted". Sólo debe aparecerle al admin.
- Modificar messages.properties y sustituir "Duration" por "Duration (in hours)".
- Quitar las activitities que ya hayan caducado para el customer. Dejar para el admin.
- Añadir enlace a la vista de curriculum para alguien sin loguear.
- Quitar orden en campo "Picture".
- Mirar el formatNumber de las monedas.
- Mirar crear gimnasios duplicados.
- Quitar enlace de "Create Activity" de la vista de Servicios.
- Añadir instrucciones de edición de las fotos de activity.

Sobre JUnit:
- Modificar fechas del Populate para que funciones todo este año.

**Comment by migrodcab** [comment]
Cambiar el nombre de la vista de listar "Activity Plans" por "Activity Plan". -> LISTO
Modificar la columna "deleted". Sólo debe aparecerle al admin. -> LISTO
Modificar messages.properties y sustituir "Duration" por "Duration (in hours)". -> LISTO
Quitar las activitities que ya hayan caducado para el customer. Dejar para el admin. -> LISTO (falta probarlo)
Quitar orden en campo "Picture". -> LISTO
Quitar enlace de "Create Activity" de la vista de Servicios. -> LISTO (se dejó, pero ahora funciona)
Añadir instrucciones de edición de las fotos de activity. -> LISTO

Commit: @45160e6b69d72ec47d5a8dc27437e9160386249c

# 

# FALTA

Controlar el activeMoment al pagar un gym para que si se deja en blanco te diga que está en blanco y que lo rellenes. Ahora mismo sale el "Cannot Commit This Operation".
Añadir enlace a la vista de curriculum para alguien sin loguear.
Mirar el formatNumber de las monedas.
Mirar crear gimnasios duplicados.
Modificar fechas del Populate para que funciones todo este año.

**Comment by migrodcab** [comment]
Cambiar el nombre de la vista de listar "Activity Plans" por "Activity Plan". -> LISTO
Modificar la columna "deleted". Sólo debe aparecerle al admin. -> LISTO
Modificar messages.properties y sustituir "Duration" por "Duration (in hours)". -> LISTO
Quitar las activitities que ya hayan caducado para el customer. Dejar para el admin. -> LISTO (falta probarlo)
Quitar orden en campo "Picture". -> LISTO
Quitar enlace de "Create Activity" de la vista de Servicios. -> LISTO (se dejó, pero ahora funciona)
Añadir instrucciones de edición de las fotos de activity. -> LISTO

Controlar el activeMoment al pagar un gym para que si se deja en blanco te diga que está en blanco y que lo rellenes. Ahora mismo sale el "Cannot Commit This Operation". -> LISTO (Hay que añadir la rest. NotNul al FeePaymentForm en el uml)
Añadir enlace a la vista de curriculum para alguien sin loguear. -> LISTO

# Commit: @e505f2cca4c21d2e35b24e78860174ac7d45a597

# FALTA

Mirar el formatNumber de las monedas.
Mirar crear gimnasios duplicados.
Modificar fechas del Populate para que funciones todo este año.
