### ISSUE TITLE
Errores encontrados por las pruebas hechas de Guillermo.

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP9Entrega#98]
Todos estos errores están en la rama de Guillermo. No he querido tirar a Develop porque voy a tener que solucionar los conflictos y me van a fallar los test. Cuando la funcionalidad esté corregida, arreglaré los test que tenga que modificar.
- testModifyRoom3 —> Problema: Se puede poner como número de asientos de una habitación un número menor que el mayor número de asientos disponibles de las actividades que tienen lugar en esa habitación.
- testDeleteRoom3 —> Problema: Se puede borrar una habitación presente en una actividad en el futuro. Para probarlo, crea una actividad con room "Habitación general" con fecha para el futuro e intenta borrar la habitación (No debería pero en código no he visto que se controle).

**Comment by migrodcab** [comment]
testDeleteRoom3 —> Problema: Se puede borrar una habitación presente en una actividad en el futuro. Para probarlo, crea una actividad con room "Habitación general" con fecha para el futuro e intenta borrar la habitación (No debería pero en código no he visto que se controle). ---> En este usas una Room que no tiene actividades.

testModifyRoom3 —> Problema: Se puede poner como número de asientos de una habitación un número menor que el mayor número de asientos disponibles de las actividades que tienen lugar en esa habitación. ---> Este ya esta arreglado, aunque el test no deberia ser positivo, ya que hay un fallo.
